### PR TITLE
Make the message passing normalizer an argument for GCN

### PR DESCRIPTION
**Pull request by mufeili**
As @haozhu233 suggested in #113 , "It might be a good idea to make it a function parameter though. People will notice this deviation from default more easily without going through the code."

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mufeili** [comment]
Can you take a look? @haozhu233

**Review by haozhu233 — APPROVED** [review]
👍👍👍

**Review by haozhu233 — APPROVED** [review]

**Review by haozhu233 — APPROVED** [review]
The addition of `gnn_norm` makes it easier for users to recognize the type of normalization used in this implementation and also gives them the ability to modify it if necessary.

**Comment by mufeili** [comment]
@haozhu233 No worries. I guess something is wrong with the CI. I've merged it. Thank you.

**Pull request merged**
